#!/bin/bash
# Grumpy librespot (raspotify) setup.
# Usage: ./setup.sh [DEVICE_NAME_SUFFIX]
#
# Installs raspotify (the apt-packaged librespot) and configures it as
# a Spotify Connect device named "Grumpy (<host>)". Idempotent.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONF_PATH="/etc/raspotify/conf"

source "$SCRIPT_DIR/../lib/common.sh"

[[ $EUID -eq 0 ]] && error "Don't run as root — script calls sudo where needed."

# ── 1. Device name ─────────────────────────────────────────────────────
SUFFIX="${1:-$(hostname -s)}"
DEVICE_NAME="Grumpy (${SUFFIX})"
info "Spotify device name: ${DEVICE_NAME}"

# ── 2. Install raspotify ───────────────────────────────────────────────
if ! command -v librespot &>/dev/null && ! dpkg -s raspotify &>/dev/null; then
    info "Adding raspotify apt repo…"
    # GPG key + sources file. Done explicitly rather than piping curl|sh.
    curl -fsSL https://dtcooper.github.io/raspotify/key.asc \
        | sudo gpg --dearmor -o /usr/share/keyrings/raspotify-archive-keyring.gpg
    echo 'deb [signed-by=/usr/share/keyrings/raspotify-archive-keyring.gpg] https://dtcooper.github.io/raspotify raspotify main' \
        | sudo tee /etc/apt/sources.list.d/raspotify.list > /dev/null

    info "Installing raspotify…"
    sudo apt-get update -qq
    sudo apt-get install -y -qq raspotify
else
    info "raspotify already installed."
fi

# ── 3. Detect audio backend ────────────────────────────────────────────
# If PipeWire is running (default on newer Pi OS desktop, and what
# linux-voice-assistant uses), use the PulseAudio shim. Otherwise
# fall back to raw ALSA.
BACKEND="alsa"
if pgrep -f pipewire-pulse &>/dev/null || pgrep -x pulseaudio &>/dev/null; then
    BACKEND="pulseaudio"
fi
info "Audio backend: ${BACKEND}"

# ── 4. Write config ────────────────────────────────────────────────────
if [[ -f "$CONF_PATH" ]]; then
    warn "$CONF_PATH exists — backing up to ${CONF_PATH}.bak"
    sudo cp "$CONF_PATH" "${CONF_PATH}.bak"
fi
sudo tee "$CONF_PATH" > /dev/null <<EOF
# Grumpy raspotify config (generated by setup.sh on $(date -Iseconds))
LIBRESPOT_NAME="${DEVICE_NAME}"
LIBRESPOT_BITRATE=320
LIBRESPOT_BACKEND=${BACKEND}
LIBRESPOT_INITIAL_VOLUME=80
LIBRESPOT_VOLUME_NORMALISATION=true
LIBRESPOT_AUTOPLAY=on
EOF
info "Wrote ${CONF_PATH}"

# ── 5. Enable + start ──────────────────────────────────────────────────
sudo systemctl daemon-reload
sudo systemctl enable raspotify
sudo systemctl restart raspotify

sleep 2
if systemctl is-active --quiet raspotify; then
    info "raspotify is running."
else
    warn "raspotify failed to start. Check: sudo journalctl -u raspotify -e"
fi

# ── 6. Wrap-up ─────────────────────────────────────────────────────────
echo
info "Done. To use:"
cat <<EOF

  1. Open Spotify on your phone or computer.
  2. Find the device picker (usually bottom-right of Now Playing).
  3. Pick "${DEVICE_NAME}".
  4. Music plays through this Pi's speaker.

  Useful commands:
    sudo systemctl status   raspotify
    sudo journalctl -u      raspotify -f
    sudo nano               ${CONF_PATH}
    sudo systemctl restart  raspotify

EOF
