#!/bin/bash
# Grumpy Kiosk Setup
# Usage: ./setup.sh [DASHBOARD_URL] [DEVICE_NAME]
#
# One-command provisioning for a Raspberry Pi kiosk.
# Safe to run multiple times (idempotent).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colours ─────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── 1. Architecture check ──────────────────────────────────────────────────
ARCH="$(uname -m)"
if [[ "$ARCH" != "aarch64" && "$ARCH" != "armv7l" ]]; then
    warn "Detected architecture: ${ARCH}"
    warn "This script is designed for Raspberry Pi (aarch64/armv7l)."
    read -rp "Continue anyway? [y/N] " answer
    [[ "$answer" =~ ^[Yy]$ ]] || exit 0
fi
info "Architecture: ${ARCH}"

# ── 2. Install Docker if missing ───────────────────────────────────────────
if command -v docker &>/dev/null; then
    info "Docker already installed: $(docker --version)"
else
    info "Installing Docker…"
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER"
    info "Docker installed. You may need to log out and back in for group membership."
fi

# Ensure docker compose plugin is available
if ! docker compose version &>/dev/null; then
    error "docker compose plugin not found. Please install docker-compose-plugin."
fi

# ── 3. Collect configuration ───────────────────────────────────────────────
DASHBOARD_URL="${1:-}"
DEVICE_NAME="${2:-}"

if [[ -z "$DASHBOARD_URL" ]]; then
    read -rp "Dashboard URL [https://192.168.5.118:5173]: " DASHBOARD_URL
    DASHBOARD_URL="${DASHBOARD_URL:-https://192.168.5.118:5173}"
fi

if [[ -z "$DEVICE_NAME" ]]; then
    DEFAULT_NAME="pi-$(hostname -s)"
    read -rp "Device name [${DEFAULT_NAME}]: " DEVICE_NAME
    DEVICE_NAME="${DEVICE_NAME:-$DEFAULT_NAME}"
fi

info "Dashboard URL: ${DASHBOARD_URL}"
info "Device name:   ${DEVICE_NAME}"

# ── 4. Write .env ──────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/.env" <<EOF
# Grumpy Kiosk Configuration (generated by setup.sh)
DASHBOARD_URL=${DASHBOARD_URL}
DEVICE_NAME=${DEVICE_NAME}
DISPLAY=:0
EOF
info "Wrote .env"

# ── 5. Disable screen blanking on host ─────────────────────────────────────
AUTOSTART_DIR="/etc/xdg/lxsession/LXDE-pi"
if [[ -d "$AUTOSTART_DIR" ]] || [[ -d "/etc/xdg/lxsession" ]]; then
    sudo mkdir -p "$AUTOSTART_DIR"
    # Preserve existing entries, add ours if missing
    AUTOSTART_FILE="$AUTOSTART_DIR/autostart"
    if [[ -f "$AUTOSTART_FILE" ]] && grep -q "xset s off" "$AUTOSTART_FILE" 2>/dev/null; then
        info "Screen blanking already disabled in autostart"
    else
        sudo tee -a "$AUTOSTART_FILE" >/dev/null <<'AUTOSTART'

# Grumpy: disable screen blanking
@xset s off
@xset -dpms
@xset s noblank
AUTOSTART
        info "Disabled screen blanking in ${AUTOSTART_FILE}"
    fi
else
    warn "LXDE autostart directory not found; skipping screen blanking config."
    warn "You may need to disable screen blanking manually."
fi

# ── 6. Allow X11 access ────────────────────────────────────────────────────
if command -v xhost &>/dev/null; then
    xhost +local: 2>/dev/null || true
    info "X11 local access granted"
else
    warn "xhost not found; container may not be able to access the display."
fi

# ── 7. Build and start ─────────────────────────────────────────────────────
info "Building and starting kiosk container…"
docker compose build
docker compose up -d
info "Container started"

# ── 8. Systemd service for boot ────────────────────────────────────────────
SERVICE_FILE="/etc/systemd/system/grumpy-kiosk.service"
sudo tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=Grumpy Kiosk (Docker Compose)
Requires=docker.service
After=docker.service graphical.target
PartOf=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${SCRIPT_DIR}
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=120

[Install]
WantedBy=graphical.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable grumpy-kiosk.service
info "Systemd service installed and enabled"

# ── 9. Done ─────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Grumpy Kiosk is running!"
echo ""
echo "  Dashboard: ${DASHBOARD_URL}?device=${DEVICE_NAME}"
echo "  Manage:    ./manage.sh {up|down|logs|restart|status|url|update}"
echo ""
echo "  The kiosk will start automatically on boot."
echo "════════════════════════════════════════════════════════════"
