#!/bin/bash
# Grumpy Kiosk Setup
# Usage: ./setup.sh [DASHBOARD_URL] [DEVICE_NAME]
#
# One-command provisioning for a Raspberry Pi kiosk.
# Safe to run multiple times (idempotent).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
source "$SCRIPT_DIR/../lib/common.sh"

# ── 1. Architecture check ──────────────────────────────────────────────────
ARCH="$(uname -m)"
if [[ "$ARCH" != "aarch64" && "$ARCH" != "armv7l" ]]; then
    warn "Detected architecture: ${ARCH}"
    warn "This script is designed for Raspberry Pi (aarch64/armv7l)."
    read -rp "Continue anyway? [y/N] " answer
    [[ "$answer" =~ ^[Yy]$ ]] || exit 0
fi
info "Architecture: ${ARCH}"

# ── 2. Docker (install if missing) ─────────────────────────────────────────
require_docker --install

# ── 3. Collect configuration ───────────────────────────────────────────────
DASHBOARD_URL="${1:-}"
DEVICE_NAME="${2:-}"

if [[ -z "$DASHBOARD_URL" ]]; then
    read -rp "Dashboard URL [https://192.168.5.118:5173]: " DASHBOARD_URL
    DASHBOARD_URL="${DASHBOARD_URL:-https://192.168.5.118:5173}"
fi

if [[ -z "$DEVICE_NAME" ]]; then
    DEFAULT_NAME="$(default_device_name)"
    read -rp "Device name [${DEFAULT_NAME}]: " DEVICE_NAME
    DEVICE_NAME="${DEVICE_NAME:-$DEFAULT_NAME}"
fi

WINDOW_SIZE="${3:-}"
if [[ -z "$WINDOW_SIZE" ]]; then
    read -rp "Window size [1920,1080]: " WINDOW_SIZE
    WINDOW_SIZE="${WINDOW_SIZE:-1920,1080}"
fi

info "Dashboard URL: ${DASHBOARD_URL}"
info "Device name:   ${DEVICE_NAME}"
info "Window size:   ${WINDOW_SIZE}"

# ── 4. Write .env ──────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/.env" <<EOF
# Grumpy Kiosk Configuration (generated by setup.sh)
DASHBOARD_URL=${DASHBOARD_URL}
DEVICE_NAME=${DEVICE_NAME}
DISPLAY=:0
WINDOW_SIZE=${WINDOW_SIZE}
EOF
info "Wrote .env"

# ── 5. Disable screen blanking + grant X11 access on host ──────────────────
# Detect compositor: labwc (Trixie/Wayland) vs LXDE (Bookworm/Xorg)
LABWC_AUTOSTART_DIR="${HOME}/.config/labwc"
LXDE_AUTOSTART_DIR="/etc/xdg/lxsession/LXDE-pi"

if [[ -d "$LABWC_AUTOSTART_DIR" ]] || command -v labwc &>/dev/null; then
    # labwc (Trixie / Wayland + Xwayland)
    mkdir -p "$LABWC_AUTOSTART_DIR"
    AUTOSTART_FILE="$LABWC_AUTOSTART_DIR/autostart"
    if grep -q "xset s off" "$AUTOSTART_FILE" 2>/dev/null; then
        info "Screen blanking already disabled in labwc autostart"
    else
        cat >> "$AUTOSTART_FILE" <<'AUTOSTART'

# Grumpy: disable screen blanking and grant X11 access to containers
xset s off &
xset -dpms &
xset s noblank &
AUTOSTART
        info "Disabled screen blanking in ${AUTOSTART_FILE}"
    fi
    # Grant X11 access (xhost must run *in* the graphical session — write it to autostart)
    if grep -q "xhost +local:" "$AUTOSTART_FILE" 2>/dev/null; then
        info "xhost already configured in labwc autostart"
    else
        cat >> "$AUTOSTART_FILE" <<'AUTOSTART'
# Grant X11 access then restart the kiosk container — Docker starts it at boot
# before Xwayland is ready, so it needs a kick once the display is up.
DISPLAY=:0 XAUTHORITY=$HOME/.Xauthority xhost +local: && \
    docker restart grumpy-kiosk &
AUTOSTART
        info "Added xhost +local: + container restart to labwc autostart (takes effect on next login)"
    fi
elif [[ -d "$LXDE_AUTOSTART_DIR" ]] || [[ -d "/etc/xdg/lxsession" ]]; then
    # LXDE (Bookworm / Xorg)
    sudo mkdir -p "$LXDE_AUTOSTART_DIR"
    AUTOSTART_FILE="$LXDE_AUTOSTART_DIR/autostart"
    if grep -q "xset s off" "$AUTOSTART_FILE" 2>/dev/null; then
        info "Screen blanking already disabled in LXDE autostart"
    else
        sudo tee -a "$AUTOSTART_FILE" >/dev/null <<'AUTOSTART'

# Grumpy: disable screen blanking
@xset s off
@xset -dpms
@xset s noblank
AUTOSTART
        info "Disabled screen blanking in ${AUTOSTART_FILE}"
    fi
    if command -v xhost &>/dev/null; then
        xhost +local: 2>/dev/null || true
        info "X11 local access granted"
    else
        warn "xhost not found; container may not be able to access the display."
    fi
else
    warn "Neither labwc nor LXDE autostart directory found; skipping screen blanking config."
    warn "You may need to disable screen blanking and run 'xhost +local:' manually."
fi

# ── 6. Build and start ─────────────────────────────────────────────────────
info "Building and starting kiosk container…"
docker compose build
docker compose up -d
info "Container started"

# ── 7. Systemd service for boot ────────────────────────────────────────────
SERVICE_FILE="/etc/systemd/system/grumpy-kiosk.service"
sudo tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=Grumpy Kiosk (Docker Compose)
Requires=docker.service
After=docker.service graphical.target
PartOf=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${SCRIPT_DIR}
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=120

[Install]
WantedBy=graphical.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable grumpy-kiosk.service
info "Systemd service installed and enabled"

# ── 7b. Periodic-restart timer ─────────────────────────────────────────────
# Long-running Chromium in kiosk mode leaks memory over days. A scheduled
# restart every 12 hours keeps the dashboard fresh without manual touch.
# Disable anytime with:  sudo systemctl disable --now grumpy-kiosk-restart.timer
RESTART_SERVICE="/etc/systemd/system/grumpy-kiosk-restart.service"
RESTART_TIMER="/etc/systemd/system/grumpy-kiosk-restart.timer"

sudo tee "$RESTART_SERVICE" >/dev/null <<EOF
[Unit]
Description=Grumpy Kiosk — scheduled restart
Requires=grumpy-kiosk.service

[Service]
Type=oneshot
ExecStart=/bin/systemctl restart grumpy-kiosk.service
EOF

sudo tee "$RESTART_TIMER" >/dev/null <<EOF
[Unit]
Description=Grumpy Kiosk — restart every 12 hours

[Timer]
# Every 12 hours, anchored to boot. Runs once ~12h after the kiosk
# starts and again 12h later, and so on.
OnBootSec=12h
OnUnitActiveSec=12h
# Spread across Pis (avoids N kiosks restarting in lockstep if you
# ever have more than one on the same schedule).
RandomizedDelaySec=15m
# Catch up a missed restart if the Pi was off when the timer should
# have fired. Prevents drift over power outages.
Persistent=true
Unit=grumpy-kiosk-restart.service

[Install]
WantedBy=timers.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now grumpy-kiosk-restart.timer
info "Scheduled restart timer installed (every 12h)"

# ── 8. Done ─────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Grumpy Kiosk is running!"
echo ""
echo "  Dashboard: ${DASHBOARD_URL}?device=${DEVICE_NAME}"
echo "  Manage:    ./manage.sh {up|down|logs|restart|status|url|update}"
echo ""
echo "  The kiosk will start automatically on boot."
echo "  Auto-restarts every 12h to clear Chromium memory leaks."
echo "    check:   systemctl list-timers grumpy-kiosk-restart.timer"
echo "    disable: sudo systemctl disable --now grumpy-kiosk-restart.timer"
echo "════════════════════════════════════════════════════════════"
