import type { DashboardConfig } from './types'

export const defaultConfig: DashboardConfig = {
  version: 1,
  theme: 'midnight',
  themeCustomAccent: '#8b5cf6',
  backgroundMode: 'solid',
  backgroundOverlay: 60,
  showTopBar: true,
  topBarFont: 'system-ui',
  topBarSize: 'large',
  topBarBold: false,
  topBarBackground: true,
  topBarScale: 100,
  topBarClockScale: 100,
  topBarWeatherScale: 100,
  topBarHeight: 90,
  widgetStartY: 90,
  topBarShadow: true,
  topBarShadowSize: 8,
  topBarShadowOpacity: 80,
  topBarWeather: true,
  topBarWeatherMode: 'current',
  topBarForecastDays: 5,
  screenRatio: 'auto',
  screensaverEnabled: true,
  screensaverTimeout: 300,
  widgetOpacity: 100,
  voiceEnabled: true,
  grid: {
    cols: 12,
    rowHeight: 80,
    margin: [12, 12],
  },
  widgets: [
    {
      id: 'clock-1',
      type: 'clock',
      layout: { x: 0, y: 0, w: 4, h: 3 },
      config: { format24h: false, showSeconds: false },
    },
    {
      id: 'weather-1',
      type: 'weather',
      layout: { x: 4, y: 0, w: 4, h: 3 },
      config: { lat: 42.3314, lon: -83.0458, units: 'imperial' },
    },
    {
      id: 'calendar-1',
      type: 'calendar',
      layout: { x: 8, y: 0, w: 4, h: 4 },
      config: { sources: [], maxEvents: 8 },
    },
    {
      id: 'todo-1',
      type: 'todo',
      layout: { x: 0, y: 3, w: 4, h: 4 },
      config: { title: 'To Do' },
    },
    {
      id: 'music-1',
      type: 'music',
      layout: { x: 4, y: 3, w: 4, h: 4 },
      config: { provider: 'none' },
    },
    {
      id: 'photos-1',
      type: 'photos',
      layout: { x: 8, y: 4, w: 4, h: 4 },
      config: { provider: 'none', interval: 30, transition: 'fade' },
    },
  ],
}
