import type { ZoneTemplate } from './zone-types'

export const zoneTemplates: ZoneTemplate[] = [
  {
    id: 'full-overlay',
    name: 'Full Overlay',
    description: 'Photo fills the screen with info overlaid in corners and a left panel',
    regions: [
      {
        id: 'top-left',
        name: 'Top Left (Clock)',
        top: '16px',
        left: '16px',
        width: 'auto',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
      {
        id: 'top-right',
        name: 'Top Right (Weather)',
        top: '16px',
        right: '16px',
        width: 'auto',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
      {
        id: 'left-panel',
        name: 'Left Panel (Calendar)',
        top: '90px',
        left: '16px',
        width: '30%',
        bottom: '16px',
        padding: '20px',
        background: 'rgba(0,0,0,0.5)',
        borderRadius: '16px',
        overflow: 'auto',
      },
      {
        id: 'bottom-right',
        name: 'Bottom Right (Info)',
        bottom: '16px',
        right: '16px',
        width: '280px',
        height: 'auto',
        padding: '16px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
    ],
  },
  {
    id: 'left-panel',
    name: 'Left Panel',
    description: 'Dark panel on left with full height, photo visible on right',
    regions: [
      {
        id: 'left-panel',
        name: 'Left Panel',
        top: '0',
        left: '0',
        width: '40%',
        height: '100%',
        padding: '24px',
        background: 'rgba(0,0,0,0.7)',
        overflow: 'auto',
      },
      {
        id: 'top-right',
        name: 'Top Right (Weather)',
        top: '16px',
        right: '16px',
        width: 'auto',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
    ],
  },
  {
    id: 'split',
    name: 'Split',
    description: '50/50 split with info panel on left and photo/widget area on right',
    regions: [
      {
        id: 'left-half',
        name: 'Left Half (Info Panel)',
        top: '0',
        left: '0',
        width: '50%',
        height: '100%',
        padding: '24px',
        background: 'rgba(0,0,0,0.7)',
        overflow: 'auto',
      },
      {
        id: 'right-half',
        name: 'Right Half (Widget Area)',
        top: '0',
        right: '0',
        width: '50%',
        height: '100%',
        padding: '24px',
        background: 'rgba(0,0,0,0.2)',
        overflow: 'auto',
      },
    ],
  },
  {
    id: 'header-content',
    name: 'Header + Content',
    description: 'Full-width header bar on top with content panels below',
    regions: [
      {
        id: 'header',
        name: 'Header Bar',
        top: '0',
        left: '0',
        width: '100%',
        height: '80px',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.6)',
      },
      {
        id: 'left-content',
        name: 'Left Content',
        top: '96px',
        left: '16px',
        width: 'calc(50% - 24px)',
        bottom: '16px',
        padding: '20px',
        background: 'rgba(0,0,0,0.5)',
        borderRadius: '16px',
        overflow: 'auto',
      },
      {
        id: 'right-content',
        name: 'Right Content',
        top: '96px',
        right: '16px',
        width: 'calc(50% - 24px)',
        bottom: '16px',
        padding: '20px',
        background: 'rgba(0,0,0,0.5)',
        borderRadius: '16px',
        overflow: 'auto',
      },
    ],
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Just a clock and one widget, the rest is beautiful photo',
    regions: [
      {
        id: 'center-top',
        name: 'Center Top (Clock)',
        top: '32px',
        left: '50%',
        width: 'auto',
        height: 'auto',
        padding: '16px 32px',
        background: 'rgba(0,0,0,0.35)',
        borderRadius: '16px',
      },
      {
        id: 'bottom-center',
        name: 'Bottom Center (Info)',
        bottom: '32px',
        left: '50%',
        width: '320px',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
    ],
  },
]

export function getTemplate(id: string): ZoneTemplate | undefined {
  return zoneTemplates.find(t => t.id === id)
}
