import type { ZoneTemplate } from './zone-types'

export const zoneTemplates: ZoneTemplate[] = [
  {
    id: 'full-overlay',
    name: 'Full Overlay',
    description: 'Photo background with calendar panel, weather, and clock overlaid',
    regions: [
      {
        id: 'top-left',
        name: 'Top Left (Clock)',
        top: '16px',
        left: '16px',
        width: 'auto',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
      {
        id: 'top-right',
        name: 'Top Right (Weather)',
        top: '16px',
        right: '16px',
        width: 'auto',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
      {
        id: 'left-panel',
        name: 'Left Panel (Calendar)',
        top: '90px',
        left: '16px',
        width: '30%',
        bottom: '16px',
        padding: '20px',
        background: 'rgba(0,0,0,0.5)',
        borderRadius: '16px',
        overflow: 'auto',
      },
      {
        id: 'bottom-right',
        name: 'Bottom Right (Info)',
        bottom: '16px',
        right: '16px',
        width: '280px',
        height: 'auto',
        padding: '16px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
    ],
  },
  {
    id: 'dakboard-classic',
    name: 'DAKboard Classic',
    description: 'Large calendar with weather header and news sidebar — classic digital display',
    regions: [
      {
        id: 'header-left',
        name: 'Header Left (Clock)',
        top: '0',
        left: '0',
        width: '35%',
        height: '80px',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.6)',
      },
      {
        id: 'header-right',
        name: 'Header Right (Weather)',
        top: '0',
        left: '35%',
        width: '65%',
        height: '80px',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.5)',
      },
      {
        id: 'main-calendar',
        name: 'Main Area (Calendar)',
        top: '80px',
        left: '0',
        width: '70%',
        bottom: '0',
        padding: '20px',
        background: 'rgba(0,0,0,0.55)',
        overflow: 'auto',
      },
      {
        id: 'right-sidebar',
        name: 'Right Sidebar (News)',
        top: '80px',
        right: '0',
        width: '30%',
        bottom: '0',
        padding: '16px',
        background: 'rgba(0,0,0,0.6)',
        overflow: 'auto',
      },
    ],
  },
  {
    id: 'agenda-focus',
    name: 'Agenda Focus',
    description: 'Upcoming events front and center with weather and news on the sides',
    regions: [
      {
        id: 'top-bar',
        name: 'Top Bar (Clock + Weather)',
        top: '0',
        left: '0',
        width: '100%',
        height: '70px',
        padding: '12px 24px',
        background: 'rgba(0,0,0,0.6)',
      },
      {
        id: 'left-news',
        name: 'Left Column (News)',
        top: '70px',
        left: '0',
        width: '25%',
        bottom: '0',
        padding: '16px',
        background: 'rgba(0,0,0,0.5)',
        overflow: 'auto',
      },
      {
        id: 'center-calendar',
        name: 'Center (Calendar/Agenda)',
        top: '70px',
        left: '25%',
        width: '50%',
        bottom: '0',
        padding: '20px',
        background: 'rgba(0,0,0,0.45)',
        overflow: 'auto',
      },
      {
        id: 'right-info',
        name: 'Right Column (Todo/Info)',
        top: '70px',
        right: '0',
        width: '25%',
        bottom: '0',
        padding: '16px',
        background: 'rgba(0,0,0,0.5)',
        overflow: 'auto',
      },
    ],
  },
  {
    id: 'left-panel',
    name: 'Left Panel',
    description: 'Dark info panel on left with calendar and news, photo visible on right',
    regions: [
      {
        id: 'left-panel',
        name: 'Left Panel',
        top: '0',
        left: '0',
        width: '40%',
        height: '100%',
        padding: '24px',
        background: 'rgba(0,0,0,0.7)',
        overflow: 'auto',
      },
      {
        id: 'top-right',
        name: 'Top Right (Weather)',
        top: '16px',
        right: '16px',
        width: 'auto',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
    ],
  },
  {
    id: 'split',
    name: 'Split',
    description: '50/50 split — calendar and news on left, widgets on right',
    regions: [
      {
        id: 'left-half',
        name: 'Left Half (Calendar)',
        top: '0',
        left: '0',
        width: '50%',
        height: '100%',
        padding: '24px',
        background: 'rgba(0,0,0,0.7)',
        overflow: 'auto',
      },
      {
        id: 'right-half',
        name: 'Right Half (Widgets)',
        top: '0',
        right: '0',
        width: '50%',
        height: '100%',
        padding: '24px',
        background: 'rgba(0,0,0,0.2)',
        overflow: 'auto',
      },
    ],
  },
  {
    id: 'family-hub',
    name: 'Family Hub',
    description: 'Calendar header, grocery list, todo, and news — family command center',
    regions: [
      {
        id: 'header',
        name: 'Header (Clock + Weather)',
        top: '0',
        left: '0',
        width: '100%',
        height: '80px',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.6)',
      },
      {
        id: 'calendar-panel',
        name: 'Calendar (Left)',
        top: '80px',
        left: '0',
        width: '40%',
        bottom: '0',
        padding: '16px',
        background: 'rgba(0,0,0,0.55)',
        overflow: 'auto',
      },
      {
        id: 'top-right-panel',
        name: 'Top Right (Todo/Grocery)',
        top: '80px',
        left: '40%',
        width: '30%',
        height: '50%',
        padding: '16px',
        background: 'rgba(0,0,0,0.5)',
        overflow: 'auto',
      },
      {
        id: 'bottom-right-panel',
        name: 'Bottom Right (News)',
        bottom: '0',
        left: '40%',
        width: '30%',
        height: 'calc(50% - 40px)',
        padding: '16px',
        background: 'rgba(0,0,0,0.5)',
        overflow: 'auto',
      },
      {
        id: 'far-right',
        name: 'Far Right (Countdown/Music)',
        top: '80px',
        right: '0',
        width: '30%',
        bottom: '0',
        padding: '16px',
        background: 'rgba(0,0,0,0.45)',
        overflow: 'auto',
      },
    ],
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Just clock and one widget — the rest is beautiful photos',
    regions: [
      {
        id: 'center-top',
        name: 'Center Top (Clock)',
        top: '32px',
        left: '50%',
        width: 'auto',
        height: 'auto',
        padding: '16px 32px',
        background: 'rgba(0,0,0,0.35)',
        borderRadius: '16px',
      },
      {
        id: 'bottom-center',
        name: 'Bottom Center (Info)',
        bottom: '32px',
        left: '50%',
        width: '320px',
        height: 'auto',
        padding: '16px 24px',
        background: 'rgba(0,0,0,0.4)',
        borderRadius: '16px',
      },
    ],
  },
]

export function getTemplate(id: string): ZoneTemplate | undefined {
  return zoneTemplates.find(t => t.id === id)
}

// Default widget assignments per template
export const templatePresets: Record<string, Record<string, string>> = {
  'full-overlay': {
    'top-left': 'clock',
    'top-right': 'weather',
    'left-panel': 'calendar',
    'bottom-right': 'todo',
  },
  'dakboard-classic': {
    'header-left': 'clock',
    'header-right': 'weather',
    'main-calendar': 'calendar',
    'right-sidebar': 'news',
  },
  'agenda-focus': {
    'top-bar': 'clock',
    'left-news': 'news',
    'center-calendar': 'calendar',
    'right-info': 'todo',
  },
  'left-panel': {
    'left-panel': 'calendar',
    'top-right': 'weather',
  },
  'split': {
    'left-half': 'calendar',
    'right-half': 'ha-entities',
  },
  'family-hub': {
    'header': 'clock',
    'calendar-panel': 'calendar',
    'top-right-panel': 'grocery',
    'bottom-right-panel': 'news',
    'far-right': 'countdown',
  },
  'minimal': {
    'center-top': 'clock',
    'bottom-center': 'weather',
  },
}

// Custom template — empty, user places their own zones
export const customTemplate: ZoneTemplate = {
  id: 'custom',
  name: 'Custom',
  description: 'Place and size your own widgets freely on the screen',
  regions: [],
}

zoneTemplates.push(customTemplate)
